# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"UREG": "00_core.ipynb",
         "WEIGHT_UNIT": "00_core.ipynb",
         "Quantity": "00_core.ipynb",
         "Unit": "00_core.ipynb",
         "unit": "00_core.ipynb",
         "with_unit": "00_core.ipynb",
         "to_dimensions": "00_core.ipynb",
         "SplitQuantity": "00_core.ipynb",
         "split": "00_core.ipynb",
         "to": "00_core.ipynb",
         "ton": "00_core.ipynb",
         "pound": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://riesfarms.github.io/runit/"

git_url = "https://github.com/riesfarms/runit/tree/main/"

def custom_doc_links(name): return None
